### ISSUE TITLE
https://maps.army.mil/covid19 redirect is broken

### ISSUE THREAD

**Issue by wellsbj** [davidstrategicaci/agc_maps.army.mil#14]
https://maps.army.mil/covid19 is supposed to redirect automatically to the uCOP portal, but i'm getting a 404.

**Comment by davidstrategicaci** [comment]
The HTML rewrite function is broken on the webserver, because if you https://maps.army.mil/covid19.html the redirect works

**Comment by davidstrategicaci** [comment]
06a7ef3
