### ISSUE TITLE
Add AGE Node Link

### ISSUE THREAD

**Issue by wellsbj** [davidstrategicaci/agc_maps.army.mil#15]
Let's add a block under community links for AGE Node, and just attach the brochure to it. 
[AGE Node Brochure.pdf](https://github.com/davidstrategicaci/agc_maps.army.mil/files/4760929/AGE.Node.Brochure.pdf)

**Comment by davidstrategicaci** [comment]
06a7ef39d9cab071c1081bde0db4a7c3230ad805
