### ISSUE TITLE
Add Water Resources Link

### ISSUE THREAD

**Issue by wellsbj** [davidstrategicaci/agc_maps.army.mil#17]
Angel requested the following:

New button called "AGC Water Resources" which links to: https://arcportal-ucop.usace.army.mil/portal/apps/View/index.html?appid=7ae7516e366b4052a74dae2c53c7fb5e

See attached for logo to use (use the second icon, the one that says "AGC Water Resources Repository"
[Water Resources Logo-FY18_UPDATED.pptx](https://github.com/davidstrategicaci/agc_maps.army.mil/files/4968418/Water.Resources.Logo-FY18_UPDATED.pptx)

**Comment by djutras2** [comment]
342df5f4f064182cfb0d849780198ff432591e7a

**Comment by davidstrategicaci** [comment]
Reduce font size in card to to reduce card overrun (for aesthetics)

**Comment by djutras2** [comment]
233794ff1eae315268bdfe06159620501104cd96
