### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by davidstrategicaci** [davidstrategicaci/agc_maps.army.mil#19]
Ordering Military Products link is broken, Should be 
https://www.nga.mil/resources/1597168879763_Military_Ordering_of_NGA_Products_and_Services.html

Also the link for the logo should be reset to 
https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/US-NationalGeospatialIntelligenceAgency-2008Seal.svg/1200px-US-NationalGeospatialIntelligenceAgency-2008Seal.svg.png

**Comment by djutras2** [comment]
34d69bd267829129061b5083025361e1952c739c
