### ISSUE TITLE
Instructions for uCOP Portal

### ISSUE THREAD

**Issue by wellsbj** [davidstrategicaci/agc_maps.army.mil#3]
Add  some text below the uCOP portal link to say: "For first time users, click HERE for USACE DMZ Access Instructions How to" and link to the attached PDF
[uCOP DMZ Access Instructions.pdf](https://github.com/davidstrategicaci/agc_maps.army.mil/files/4518848/uCOP.DMZ.Access.Instructions.pdf)

**Comment by davidstrategicaci** [comment]
2e2952d
