### ISSUE TITLE
Change Banner Background Image Format

### ISSUE THREAD

**Issue by wellsbj** [davidstrategicaci/agc_maps.army.mil#6]
Who: Brett Patrick
Priority: Low

Change PNGs to JPGs   or GIFs. Rationale: reduce network bandwidth requirements.

**Comment by davidstrategicaci** [comment]
Gif too low a quality for some images 

![agc](https://user-images.githubusercontent.com/15834449/80376161-0677b300-885f-11ea-869d-ddc318c6bfe2.gif)
![agc](https://user-images.githubusercontent.com/15834449/80376173-0aa3d080-885f-11ea-9fb3-a5a51dd4a23d.png)


Jpeg losses the transparency (alpha band).  I still dont think bandwidth constraint is a concern anyway.

**Comment by davidstrategicaci** [comment]
I change the images that dont need transparency (backrounds and upcop) to jpg. 
f5e32bf6fcc935f16afcd562fbb65133b6e89d70
