### ISSUE TITLE
Add Keywords to HTML Header

### ISSUE THREAD

**Issue by wellsbj** [davidstrategicaci/agc_maps.army.mil#7]
Who: Brett Patrick
Priority: Low

Add   keywords:  In the HTML header add a   meta tag with the following keywords:      <meta name="keywords" content="Map, Maps, Geo, GEOINT,   Geospatial, Imagery, SSGF, Topo, Topographic, Globe, Basemap, Base Map, COE,   Data, Elevation, Feature, Foundation, GEOID, Raster, Route, Vector, GET, GPC,   WMS, WMTS, WCS, WFS, 12Y, AGC, Army, Buckeye, CADRG, CCv2, CIB, CPCE, DCGS-A,   DMS, DTED, ECRG, Geoname, GeoPackage, GPS, LiDAR, MCE, MGRS, MHHCE, NGA, OSM,   UTM, SFG, SGF, SSFG">          Rationale: COE TAB approved SSGF ETSS #2 D-ECP Appendix E. 

Note: this   intentionally includes a few misspellings of SSGF to enhance search results   where meta tags are used.
--

**Comment by davidstrategicaci** [comment]
89fc20a
